kanta = int(input("Anna suorakulmion kanta: \n"))
korkeus = int(input("Anna suorakulmion korkeus: \n"))
pintaA = str(kanta * korkeus)
piiri = str(kanta * 2 + korkeus * 2)
print("Suorakulmion pinta-ala on: " + pintaA + " ja piiri on: " + piiri + ".")
